blank_issues_enabled: true
contact_links:
  - name: Read the README
    url: https://github.com/NimbusVacuum/lovelace-nimbus-map-card#readme
    about: Did you read the README?
  - name: How to clear cache
    url: https://github.com/NimbusVacuum/lovelace-nimbus-map-card/issues/85#issuecomment-790248620
    about: "Have you restarted Home Assistant? If that didn't work, have you cleared your cache? Several times? Like, 20+ times? I'm serious. Do that first."
  - name: Map card release notes
    url: https://github.com/NimbusVacuum/lovelace-nimbus-map-card/releases
    about: Did something break after updating? Did you read the release notes?
  - name: Nimbus release notes
    url: https://github.com/NimbusVacuum/Nimbus/releases
    about: "Did you also read Nimbus's release notes?"
